=== F5Networks/f5-appsvcs-extension/schema/3.0.0/as3-request-schema.json
{
 "$id": "urn:uuid:85626792-9ee7-46bb-8fc8-4ba708cfdc1d",
 "$schema": "http://json-schema.org/draft-07/schema#",

 "title": "AS3 Request",
 "description": "AS3 request body",
 "type": "object",

 "properties": {
    "class": {
        "title": "Class",
        "description": "Indicates the structure of this request",
        "type": "string",
        "enum": [ "AS3" ]
    },
    "action": {
        "title": "Action",
        "description": "Indicates desired action:  'deploy' means deploy the included declaration to targetHost; 'dry-run' does NOT deploy the declaration but does do everything short of changing targetHost's configuration; 'redeploy' causes an old declaration from targetHost's declaration history to be re-deployed (property redeployAge (default 0) selects the old declaration, and note redeployUpdateMode as well); 'retrieve' returns a copy of a previously-deployed declaration; 'remove' deletes the declaration or declaration component." ,
        "type": "string",
        "enum": [ "deploy", "dry-run", "redeploy", "retrieve", "remove" ]
    },
    "redeployAge": {
        "title": "Redeploy age",
        "description": "For action=redeploy (only), chooses which old declaration to deploy again.  Value 0 (default) means re-deploy the most recent declaration (the one which set the current configuration of targetHost-- useful to erase changes introduced by manual configuration).  Value 1 means re-deploy the declaration prior to the most-recent one, etc.  Note that whenever re-deploying an old declaration causes ADC configuration changes, that declaration becomes the current declaration (age 0) and the ages of all other declarations in the history increase (0 => 1, 1 => 2, u.s.w.)",
        "type": "integer",
        "minimum": 0,
        "maximum": 15,
        "default": 0
    },
    "redeployUpdateMode": {
        "title": "Redeploy update mode",
        "description": "Value 'original' (default) means re-deploy the chosen declaration using its original updateMode (which if not explicitly specified in that declaration will default to 'selective').  Otherwise, forces the updateMode for re-deployment to 'complete' or 'selective' as specified.  Remember, 'selective' updates do not affect Tenants not explicitly named.  To simply roll-back the targetHost configuration to the state it had immediately after deploying some earlier declaration, put 'complete' here (that will remove Tenants created later than the redeployAge declaration).  To use action=redeploy as a simple roll-back facility, always deploy (updateMode=)complete declarations.",
        "type": "string",
        "enum": [ "original", "complete", "selective" ],
        "default": "original"
    },
    "persist": {
        "title": "Persist on device",
        "description": "When true (default) make the whole working configuration persistent on targetHost after (and only if) this request deploys any changes.  If false, leave the working configuration in memory only (from which it may be lost if targetHost restarts)",
        "type": "boolean",
        "default": true
    },
    "syncToGroup": {
        "title": "Sync to device group",
        "description": "Name (like /Common/my_dg) of config-sync group TO which targetHost configuration should be synchronized after (and only if) this request deploys any changes.  When empty (default) this request will not affect config-sync at all.  Leave undefined or empty whenever you use auto-sync or manage configuration synchronization separately",
        "type": "string",
        "default": ""
    },
    "historyLimit": {
        "title": "History limit",
        "description": "This value (default 4) limits the number of previously-deployed declarations saved on targetHost for review using GET and for use with POST action=redeploy and redeployAge=N.  The limit includes the current and immediately-previous declarations so may not be less than two",
        "type": "number",
        "minimum": 2,
        "maximum": 15,
        "default": 4
    },

    "logLevel": {
        "title": "Log level",
        "description": "Controls level of detail in logs using RFC 5424 severity levels (default is 'error').  Portions of declaration may use different logLevels",
        "type": "string",
        "enum": [
            "emergency", "alert", "critical", "error",
            "warning", "notice", "info", "debug"
        ],
        "default": "error"
    },
    "trace": {
        "title": "Trace",
        "description": "If true, a detailed trace of the configuration process will be created for subsequent analysis (default false).  May be overridden on a per-Declaration and/or per-Tenant basis.  Warning:  trace files may contain sensitive configuration data",
        "type": "boolean",
        "default": false
    },
    "retrieveAge": {
        "title": "Retrieve age",
        "description": "Use this property with action=retrieve.  You can usually get a copy of the declaration most recently deployed to targetHost, and often copies of previously-deployed declarations are also available.  Value 0 (default) means 'the last-deployed declaration,' value 1 means 'the declaration previous to 0' and so-forth.  To get a list of available declarations, set value 'list'",
        "type": [ "integer", "string" ],
        "minimum": 0,
        "pattern": "^list$",
        "default": 0
    },
    "targetHost": {
        "title": "Target host",
        "description": "Hostname or IP address of ADC to which request applies (default localhost)",
        "type": "string",
        "anyOf": [
            { "format": "hostname" },
            { "format": "f5ip" }
        ],
        "default": "localhost"
    },
    "targetPort": {
        "title": "Target port",
        "description": "TCP port number of management service on targetHost; default 0 means auto-discover",
        "type": "integer",
        "minimum": 0,
        "maximum": 65535,
        "default": 0
    },
    "targetUsername": {
        "title": "Target username",
        "description": "Username of principal authorized to modify configuration of targetHost (may not include the character ':').  NOTE:  this is generally not required to configure 'localhost' because client authentication and authorization precede invocation of AS3.  It is also not required for any targetHost if you populate targetTokens",
        "type": "string",
        "pattern": "^[^:]{0,254}$"
    },
    "targetPassphrase": {
        "title": "Target passphrase",
        "description": "Passphrase for targetUsername account.  This is generally not required to configure 'localhost' and is not required when you populate targetTokens",
        "type": "string",
        "pattern": "^.{0,254}$"
    },
    "targetTokens": {
        "title": "Target tokens",
        "description": "One or more HTTP headers (each a property, like 'X-F5-Auth-Token': 'ABC123') to be sent with queries to the targetHost management service as authentication/authorization tokens",
        "type": "object",
        "patternProperties": {
            "^[^\\x00-\\x20:\\x7f-\\xff]{1,254}$": {
                "title": "HTTP header",
                "type": "string",
                "pattern": "^[^\\x00-\\x1f\\x7f-\\xff]{0,8192}$"
            }
        },
        "additionalProperties": false
    },
    "targetTimeout": {
        "title": "Target timeout",
        "description": "Maximum delay allowed while communicating with targetHost device (seconds, default 150)",
        "type": "integer",
        "minimum": 1,
        "maximum": 900,
        "default": 150
    },
    "resourceTimeout": {
        "title": "Resource timeout",
        "description": "Maximum delay allowed while communicating with URL resources (seconds, default 5)",
        "type": "integer",
        "minimum": 1,
        "maximum": 900,
        "default": 5
    },

    "declaration": {
        "title": "Declaration",
        "description": "Declaration to deploy to targetHost",
        "type": "object",
        "$comment": "See adc-schema.json"
    }
 },

 "required": [ "class" ]
}

=== F5Networks/f5-appsvcs-extension/examples/declarations/example-c3d.json
{
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "logLevel": "debug",
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.9.0",
        "id": "C3DFeatures",
        "label": "C3D Test",
        "remark": "test",
        "Sample_C3D": {
            "class": "Tenant",
            "appC3D": {
                "class": "Application",
                "webtls": {
                    "class": "TLS_Server",
                    "certificates": [
                        {
                            "matchToSNI": "www.test.domain.com",
                            "certificate": "webcert1"
                        },
                        {
                            "certificate": "webcert2"
                        }
                    ],
                    "authenticationMode": "request",
                    "authenticationTrustCA": {
                        "bigip": "/Common/dev_chain.crt"
                    },
                    "crlFile": {
                        "bigip": "/Common/dev_crl.crl"
                    },
                    "allowExpiredCRL": true,
                    "c3dOCSPUnknownStatusAction": "ignore",
                    "c3dOCSP": {
                        "use": "ocsp"
                    },
                    "c3dEnabled": true
                },
                "webcert1": {
                    "class": "Certificate",
                    "remark": "test",
                    "certificate": "-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----",
                    "privateKey": "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----"
                },
                "webcert2": {
                    "class": "Certificate",
                    "remark": "test",
                    "certificate": "-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----",
                    "privateKey": "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----"
                },
                "ocsp": {
                    "class": "Certificate_Validator_OCSP",
                    "dnsResolver": { "bigip": "/Common/10.10.10.10" },
                    "responderUrl": "http://oscp.responder.test.com",
                    "timeout": 299
                },
                "clienttls": {
                    "class": "TLS_Client",
                    "clientCertificate": "defaultCert",
                    "crlFile": { "bigip": "/Common/c3d_crl.crl" },
                    "allowExpiredCRL": true,
                    "c3dEnabled": true,
                    "c3dCertificateAuthority": "c3dCA",
                    "c3dCertificateLifespan": 360,
                    "c3dCertificateExtensions": ["subject-alternative-name"],
                    "trustCA": { "bigip": "/Common/c3d_chain.crt"}
                },
                "c3dCA": {
                    "class": "Certificate",
                    "certificate": "-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----",
                    "privateKey": "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----"
                },
                "defaultCert": {
                    "class": "Certificate",
                    "certificate": {"bigip":"/Common/default.crt"},
                    "privateKey": {"bigip":"/Common/default.key"}
                }
           }
        }
    }
}

=== F5Networks/f5-appsvcs-extension/examples/declarations/example-tcp-analytics.json
{
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
      "class": "ADC",
      "schemaVersion": "3.14.0",
      "label": "TCP Analytics Example",
      "remark": "Service_TCP with TCP Analytics",
      "TcpAnalytics": {
        "class": "Tenant",
        "tcpAnalytics": {
          "class": "Application",
          "service": {
            "class": "Service_TCP",
            "virtualAddresses": [
              "10.0.5.10"
            ],
            "virtualPort": 1344,
            "pool": "svc_pool",
            "profileAnalyticsTcp": { "use": "myAnalyticsTcp" }
          },
          "myAnalyticsTcp": {
              "class": "Analytics_TCP_Profile",
              "collectedStatsInternalLogging": true,
              "collectedStatsExternalLogging": true,
              "externalLoggingPublisher": { "bigip": "/Common/local-db-publisher" },
              "collectedByClientSide": true,
              "collectedByServerSide": true,
              "collectRemoteHostIp": true,
              "collectRemoteHostSubnet": true,
              "collectNexthop": true,
              "collectContinent": true,
              "collectCountry": true,
              "collectRegion": true,
              "collectCity": true,
              "collectPostCode": true
          },
          "svc_pool": {
            "class": "Pool",
            "members": [{
              "servicePort": 1344,
              "serverAddresses": [
                "192.0.5.10",
                "192.0.5.11"
              ]
            }]
          }
        }
      }
    }
}

=== F5Networks/f5-appsvcs-extension/examples/declarations/example-mcp-irule.json
{
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.0.0",
        "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
        "label": "Sample 1",
        "remark": "Simple MCP application",
        "Sample_01": {
            "class": "Tenant",
            "A1": {
                "class": "Application",
                "mySSEProfile": {
                    "class": "SSE_Profile"
                },
                "myJSONProfile": {
                    "class": "JSON_Profile"
                },
                "service": {
                    "class": "Service_HTTP",
                    "virtualAddresses": [
                        "10.0.1.10"
                    ],
                    "pool": "mcp_pool",
                    "iRules": [
                        "persistenceiRule"
                    ],
                    "persistenceMethods": [
                        "cookie"
                    ],
                    "proflieSSE": {
                        "use": "mySSEProfile"
                    },
                    "profileJSON": {
                        "use": "myJSONProfile"
                    }
                },
                "mcp_pool": {
                    "class": "Pool",
                    "monitors": [
                        "http"
                    ],
                    "members": [
                        {
                            "servicePort": 80,
                            "serverAddresses": [
                                "192.0.1.10",
                                "192.0.1.11"
                            ]
                        }
                    ]
                },
                "persistenceiRule": {
                    "class": "iRule",
                    "iRule": "when HTTP_REQUEST {\n    set is_req_to_sse_endpoint false\n\n    if { [HTTP::path] eq \"/sse\" } {\n        # SSE endpoint for 2024-11-05 version of MCP Spec\n        set is_req_to_sse_endpoint true\n        return\n    }\n\n    if { [HTTP::path] eq \"/messages\" } {\n        # Message endpoint for 2024-11-05 version of MCP Spec\n        # Decode persist secret in URI of request\n        set query_string [HTTP::query]\n        set f5_sess_found false\n        set new_query_string \"\"\n        set query_separator \"\"\n        set queries [split $query_string \"&\"]\n        foreach query $queries {\n            if { $f5_sess_found } {\n                # On queries after the F5 session. Retain them.\n                append new_query_string \"${query_separator}${query}\"\n                set query_separator \"&\"\n            } elseif { [string match \"f5Session=*\" $query] } {\n                # Here's our persistence secret. Handle It.\n                set pmbr_info [URI::decode [string range $query 10 end]]\n                set pmbr_parts [split $pmbr_info \",\"]\n                if { [llength $pmbr_parts] == 2} {\n                    set pmbr_tuple [split [lindex $pmbr_parts 1] \":\"]\n                    if { [llength $pmbr_tuple] == 2 } {\n                        # Found a valid pool record. Tell the proxy.\n                        pool [lindex $pmbr_parts 0] member [lindex $pmbr_parts 1]\n                        set f5_sess_found true\n                    } else {\n                        HTTP::respond 404 noserver\n                        return\n                    }\n                } else {\n                    HTTP::respond 404 noserver\n                    return\n                }\n            } else {\n                # Another query. Haven't found the F5 secret yet.\n                # Append to query string we will forward.\n                append new_query_string \"${query_separator}${query}\"\n                set query_separator \"&\"\n            }\n        }\n        if { $f5_sess_found } {\n            HTTP::query $new_query_string\n        } else {\n            HTTP::respond 404 noserver\n        }\n        return\n    }\n\n    if { [HTTP::path] eq \"/mcp\" } {\n        # MCP endpoint for 2025-03-26 version of MCP Spec\n        if { [HTTP::header exists \"Mcp-Session-Id\"] } {\n            # Decode persist secret in session header\n            set header_value [HTTP::header \"Mcp-Session-Id\"]\n            set header_parts [split $header_value \",\"]\n\n            if { [llength $header_parts] == 3 } {\n                set pmbr_tuple [split [lindex $header_parts 1] \":\"]\n                if { [llength $pmbr_tuple] == 2 } {\n                    HTTP::header replace \"Mcp-Session-Id\" [lindex $header_parts 2]\n                    pool [lindex $header_parts 0] member [lindex $header_parts 1]\n                } else {\n                    HTTP::respond 404 noserver\n                }\n            } else {\n                HTTP:: respond 404 noserver\n            }\n        }\n    }\n}\n\nwhen HTTP_RESPONSE {\n    if { [HTTP::header exists \"Mcp-Session-Id\"] } {\n        # Using session header - 2025-03-26 spec - insert persist secret\n\n        # Get the current pool member's IP and port\n        set pool_member [LB::server pool],[IP::remote_addr]:[TCP::remote_port]\n\n        # Prepend the pool member IP and port to the header value\n        set header_value [HTTP::header \"Mcp-Session-Id\"]\n        set new_header_value \"$pool_member,$header_value\"\n        HTTP::header replace \"Mcp-Session-Id\" $new_header_value\n    }\n}\n\nwhen SSE_RESPONSE {\n    if { $is_req_to_sse_endpoint && [SSE::field get event] eq \"endpoint\" } {\n        # Server sending MCP message endpoint. Insert persist secret\n        set sse_data [SSE::field get data]\n\n        # Extract existing URI info from SSE endpoint data\n        set old_path [URI::path $sse_data][URI::basename $sse_data]\n        set old_queries [URI::query $sse_data]\n        if { [string length $old_queries] == 0} {\n            set query_separator \"\"\n        } else {\n            set query_separator \"&\"\n        }\n\n        # Create a new query param encoding current pool member's info\n        set new_query \"f5Session=[URI::encode [LB::server pool],[IP::remote_addr]:[TCP::remote_port]]\"\n\n        # Construct new full endpoint, inserting F5 session info\n        set new_endpoint \"${old_path}?${new_query}${query_separator}${old_queries}\"\n        SSE::field set data $new_endpoint\n    }\n}",
                    "expand": true
                }
            }
        }
    }
}

=== F5Networks/f5-appsvcs-extension/examples/declarations/example-service-tcp-with-source-destination-lists.json
{
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.46.0",
        "id": "addressList",
        "Tenant": {
            "class": "Tenant",
            "Application": {
                "class": "Application",
                "sourceAddressList": {
                    "class": "Firewall_Address_List",
                    "addresses": [
                        "192.168.2.10/32",
                        "192.168.2.50-192.168.2.60"
                    ]
                },
                "destinationAddressList1": {
                    "class": "Firewall_Address_List",
                    "addresses": [
                        "192.168.2.1-192.168.2.10"
                    ]
                },
                "destinationAddressList2": {
                    "class": "Firewall_Address_List",
                    "addresses": [
                        "192.168.2.20/32"
                    ]
                },
                "destinationAddressList3": {
                    "class": "Firewall_Address_List",
                    "addresses": [
                        "192.168.2.100/32"
                    ],
                    "addressLists": [
                        {
                            "use": "destinationAddressList1"
                        },
                        {
                            "use": "destinationAddressList2"
                        }
                    ]
                },
                "portList": {
                    "class": "Firewall_Port_List",
                    "ports": [
                        8080,
                        "1-999"
                    ]
                },
                "tcpService": {
                    "class": "Service_TCP",
                    "sourceAddress": {
                        "use": "sourceAddressList"
                    },
                    "virtualAddresses": {
                        "use": "destinationAddressList3"
                    },
                    "virtualPort": {
                        "use": "portList"
                    }
                }
            }
        }
    }
}
